pipeline {
    agent any

    environment {
        IMAGE_TAG = "${env.GIT_COMMIT[0..7]}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                dir('DeliveryService') {
                    sh "docker build -t delivery-service:${IMAGE_TAG} ."
                }
            }
        }

    }

    post {
        success {
            echo " Delivery service CI passed - Image: delivery-service:${IMAGE_TAG}"
        }
        failure {
            echo " Delivery service CI failed"
        }
        always {
            sh "docker rmi delivery-service:${IMAGE_TAG} || true"
            cleanWs()
        }
    }
}